// examples/tanstack-start/src/routes/index.tsx
import {
  createFileRoute,
  useRouter,
} from "@tanstack/react-router";
import { getApi } from "@/userbase";
import { createServerFn, useServerFn } from "@tanstack/react-start";
import { Footer } from "@/components/Footer";
import { List } from "@/components/List";

export const completeTodo = createServerFn({ method: "POST" })
  .inputValidator(
    (data) => data as { done: boolean; id: number; title: string },
  )
  .handler(async ({ data: todo }) => {
    try {
      const api = await getApi({});
      await api.data.updateOne("todos", todo.id, {
        done: !todo.done,
      });
      console.log("state updated in db");
    } catch (error) {
      console.log(error);
    }
  });

export const deleteTodo = createServerFn({ method: "POST" })
  .inputValidator((data) => data as { id: number })
  .handler(async ({ data }) => {
    try {
      const api = await getApi({});
      await api.data.deleteOne("todos", data.id);
      console.log("todo deleted from db");
    } catch (error) {
      console.log(error);
    }
  });

export const createTodo = createServerFn({ method: "POST" })
  .inputValidator((data) => data as { title: string })
  .handler(async ({ data }) => {
    try {
      const api = await getApi({});
      await api.data.createOne("todos", { title: data.title });
      console.log("todo created in db");
    } catch (error) {
      console.log(error);
    }
  });

export const getTodo = createServerFn({ method: "POST" }).handler(async () => {
  const api = await getApi({});
  const limit = 5;
  const todos = await api.data.readMany("todos", { limit, sort: "-id" });
  const total = todos.body.meta.total as number;
  return { total, todos, limit };
});

export const Route = createFileRoute("/")({
  ssr:false,
  component: App,
  loader: async () => {
    return await getTodo();
  },
});

function App() {
  const { todos, total, limit } = Route.useLoaderData();
  const router = useRouter();

  const updateTodo = useServerFn(completeTodo);
  const removeTodo = useServerFn(deleteTodo);
  const addTodo = useServerFn(createTodo);

  return (
    <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20">
      <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
        <div className="flex flex-row items-center ">
          <img
            className="dark:invert size-18"
            src="/tanstack-circle-logo.png"
            alt="TanStack logo"
          />
          <div className="ml-3.5 mr-2 font-mono opacity-70">&amp;</div>
          <img
            className="dark:invert"
            src="/userbase.svg"
            alt="userbase logo"
            width={183}
            height={59}
          />
        </div>
        <Description />
        <div className="flex flex-col border border-foreground/15 w-full py-4 px-5 gap-2">
          <h2 className="font-mono mb-1 opacity-70">
            <code>What's next?</code>
          </h2>
          <div className="flex flex-col w-full gap-2">
            {total > limit && (
              <div className="bg-foreground/10 flex justify-center p-1 text-xs rounded text-foreground/40">
                {total - limit} more todo(s) hidden
              </div>
            )}
            <div className="flex flex-col gap-3">
              {todos.map((todo) => (
                <div className="flex flex-row" key={String(todo.id)}>
                  <div className="flex flex-row flex-grow items-center gap-3 ml-1">
                    <input
                      type="checkbox"
                      className="flex-shrink-0 cursor-pointer"
                      defaultChecked={!!todo.done}
                      onChange={async () => {
                        await updateTodo({ data: todo });
                        router.invalidate();
                      }}
                    />
                    <div className="text-foreground/90 leading-none">
                      {todo.title}
                    </div>
                  </div>
                  <button
                    type="button"
                    className="cursor-pointer grayscale transition-all hover:grayscale-0 text-xs "
                    onClick={async () => {
                      await removeTodo({ data: { id: todo.id } });
                      router.invalidate();
                    }}
                  >
                    ❌
                  </button>
                </div>
              ))}
            </div>
            <form
              className="flex flex-row w-full gap-3 mt-2"
              key={todos.map((t) => t.id).join()}
              onSubmit={async (e) => {
                e.preventDefault();
                const formData = new FormData(e.currentTarget);
                const title = formData.get("title") as string;
                await addTodo({ data: { title } });
                router.invalidate();
                e.currentTarget.reset();
              }}
            >
              <input
                type="text"
                name="title"
                placeholder="New todo"
                className="py-2 px-4 flex flex-grow rounded-sm bg-foreground/10 focus:bg-foreground/20 transition-colors outline-none"
              />
              <button type="submit" className="cursor-pointer">
                Add
              </button>
            </form>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}

const Description = () => (
  <List
    items={[
      "Get started with a full backend.",
      "Focus on what matters instead of repetition.",
    ]}
  />
);

// examples/solid/src/routes/index.tsx
import type { DB } from "bknd";
import { Suspense } from "solid-js";
import { Footer } from "~/components/Footer";
import { List } from "~/components/List";
import { getApi } from "~/lib/bknd";
import { action, redirect, useAction, useSubmission } from "@solidjs/router";
import { query, createAsync } from "@solidjs/router";

type Todo = DB['todos'];

export const getTodo = async () => {
  "use server"
  const api = await getApi({});
  const limit = 5;
  const todos = await api.data.readMany("todos");
  const total = todos.body.meta.total as number;
  return { total, todos: todos as unknown as Todo[], limit };
};

const getTodosFromServer = query(async () => await getTodo(), "getTodosFromServer");


const createTodo = action(async (formData: FormData) => {
  "use server"
  const title = formData.get("title") as string;
  const api = await getApi({});
  await api.data.createOne("todos", { title });
  throw redirect("/", { revalidate: getTodosFromServer.keyFor() });
}, "createTodo");



const completeTodo = action(async (todo: Todo) => {
  "use server"
  const api = await getApi({});
  await api.data.updateOne("todos", todo.id, {
    done: !todo.done,
  });
  throw redirect("/", { revalidate: getTodosFromServer.keyFor() });
}, "completeTodo");


const deleteTodo = action(async (todo: Todo) => {
  "use server"
  const api = await getApi({});
  await api.data.deleteOne("todos", todo.id);
  throw redirect("/", { revalidate: getTodosFromServer.keyFor() });
}, "deleteTodo");

export default function Home() {
  const data = createAsync(() => getTodosFromServer());

  const submission = useSubmission(createTodo);

  const updateTodo = useAction(completeTodo);
  const removeTodo = useAction(deleteTodo);

  return (
    <div class="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 ">
      <main class="flex flex-col gap-8 row-start-2 items-center sm:items-start">
        <div class="flex flex-row items-center ">
          <img
            class="dark:invert size-18"
            src="/solid.svg"
            alt="Solid Start logo"
          />
          <div class="ml-3.5 mr-2  opacity-70">&amp;</div>
          <img
            class="dark:invert"
            src="/bknd.svg"
            alt="bknd logo"
            width={183}
            height={59}
          />
        </div>
        <Description />
        <Suspense>
          <div class="flex flex-col border border-foreground/15 w-full py-4 px-5 gap-2">
            <h2 class=" mb-1 opacity-70">
              <code>What's next?</code>
            </h2>
            <div class="flex flex-col w-full gap-2">
              {(data()?.total ?? 0) > (data()?.limit ?? 0) && (
                <div class="bg-foreground/10 flex justify-center p-1 text-xs rounded text-foreground/40">
                  {(data()?.total ?? 0) - (data()?.limit ?? 0)} more todo(s) hidden
                </div>
              )}
              <div class="flex flex-col gap-3">
                {data()?.todos?.
                  splice(0, data()?.limit ?? 0)
                  .map((todo) => (
                    <div class="flex flex-row">
                      <div class="flex flex-row flex-grow items-center gap-3 ml-1">
                        <input
                          type="checkbox"
                          class="flex-shrink-0 cursor-pointer"
                          checked={!!todo.done}
                          onChange={async () => {
                            await updateTodo(todo);
                          }}
                        />
                        <div class="text-foreground/90 leading-none">
                          {todo.title}
                        </div>
                      </div>
                      <button
                        type="button"
                        class="cursor-pointer grayscale transition-all hover:grayscale-0 text-xs "
                        onClick={async () => {
                          await removeTodo(todo);
                        }}
                      >
                        ❌
                      </button>
                    </div>
                  ))}
              </div>
              <form
                class="flex flex-row w-full gap-3 mt-2"
                action={createTodo}
                method="post"
              >
                <input
                  type="text"
                  name="title"
                  placeholder="New todo"
                  class="py-2 px-4 flex flex-grow rounded-sm bg-foreground/10 focus:bg-foreground/20 transition-colors outline-none"
                />
                <button type="submit" class="cursor-pointer" disabled={submission.pending}>
                  {submission.pending ? "Adding..." : "Add"}
                </button>
              </form>
            </div>
          </div>
        </Suspense>
      </main>
      <Footer />
    </div>);
}



const Description = () => (
  <List
    items={[
      "Get started with a full backend.",
      "Focus on what matters instead of repetition.",
    ]}
  />
);
